name: Checks
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Spellchecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: rust-lang-ru/common-configs
        path: common-configs
    - name: Get all changed markdown files
      uses: tj-actions/changed-files@v45
      id: changed_files
      with:
        files: |
           async-book-ru/**/*.md
           README.md
    - name: List changed files
      if: steps.changed_files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
    - uses: funkill/spellcheck-github-actions@hunspell-support-action
      if: steps.changed_files.outputs.any_changed == 'true'
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
  gitlocalize-bug-checking:
    name: Checking Gitlocalize bugs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rust-lang-ru/simpleinfra/gitocalize-bug-checker@master
